# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0436c843ea687bb6714b87a2f1e529a2f3de453fef08301f3d84bbc110bd9eea640fac28bd191ce4559b9c223b8b6d7b40814d30aafac48eecf917de8aaceb16

test:
  secret_key_base: 89d6398fe11cc706b9809b410005cc91ce79dae81c3a474154c33cdc02bd861acb15dd3658e298d5121d57fc74574f54f0b58bfbacdc2cbda30545464fe0ff1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
